sudo: required
services:
  - docker

before_install:
  - dokcer build -t thuannhoden5/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thuannhodne5/react-test npm test

after_success:
  - docker build -t thuannhoden5/multi-client ./client
  - docker build -t thuannhoden5/multi-nginx ./nginx
  - docker build -t thuannhoden5/multi-server ./server
  - dokcer build -t thuannhoden5/multi-worker ./worker
  # login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push thuannhoden5/multi-client
  - docker push thuannhoden5/multi-nginx
  - docker push thuannhoden5/multi-server
  - docker push thuannhoden5/multi-worker